name: gbfossilprep

services:
  frontend:
    build: ./frontend
    container_name: ${COMPOSE_PROJECT_NAME:-gbfossilprep}-frontend
    ports:
      - "${FRONTEND_PORT:-21819}:80"
    restart: unless-stopped
